:pick: Generate an image from a Prompt using SVG.io
alexrudd2/saxi pull request #151
Opened 2024-11-03 20:57 UTC by juli4nb4dillo

I'm using this AI image generator: https://api.svg.io/v1/docs
To make an image from a prompt you need an API Key.

![Screenshot 2024-11-03 at 2 57 04 PM](https://github.com/user-attachments/assets/d56620a8-530d-441d-9d00-87f7d9456735)

2024-11-03 21:11 UTC, juli4nb4dillo commented
sorry for the formatting, my vscode is set up with one of the default formatters for javascript.

2024-11-07 17:23 UTC, alexrudd2 commented
> sorry for the formatting, my vscode is set up with one of the default formatters for javascript.


(╯°□°)╯︵ ┻━┻

Well, fix it then :)

2024-11-07 17:35 UTC, alexrudd2 requested changes
I don't have an API key and therefore can't test anything.  :(

So my review is mostly just superficial comments to fit in with the rest of the codebase.


I think the "AI" tab should go into the "More" tab.  And perhaps the prompt could go in the svg drag-n-drop target?

2024-11-07 17:35 UTC, alexrudd2 commented on src/ui.tsx
> +      <label title="propmpt">Prompt
`title="prompt"`

2024-11-07 17:35 UTC, alexrudd2 commented on src/ui.tsx
> +      {state.svgIoOptions.status ? <span>{state.svgIoOptions.status}</span> : <button onClick={generateImage}>Generate!</button>}
This button should be disabled with no API key, otherwise it appears to do something when clicked and fails silently.

2024-11-07 17:35 UTC, alexrudd2 commented on src/ui.tsx
> +  svgIoOptions: { apiKey: '', prompt: '', status: '', vecType: 'FLAT_VECTOR' },
follow the `defaultOptions` pattern

2024-11-08 23:01 UTC, juli4nb4dillo commented
I undid most of the formatting, it needs work, but I don't want to obscure the stuff I did because of it.
I'll make a new PR with re-formatting, it's awful and inconsistent all around.

2024-11-08 23:04 UTC, juli4nb4dillo commented
> I don't have an API key and therefore can't test anything. :(
I'll send you my key

> I think the "AI" tab should go into the "More" tab. And perhaps the prompt could go in the svg drag-n-drop target?
I like my own tab, but I like the prompt idea, If I figure out how to pop-up modals and do a 2-step workflow I'll do it.

2024-11-09 14:22 UTC, alexrudd2 commented
> I undid most of the formatting, it needs work, but I don't want to obscure the stuff I did because of it. I'll make a new PR with re-formatting, it's awful and inconsistent all around.

https://github.com/alexrudd2/saxi/issues/96

Also, for a while my priority had been to keep things as close to https://github.com/nornagon/saxi as possible, so they could be upstreamed: https://github.com/users/alexrudd2/projects/1.  However, that looks less and less likely (nornagon has a young child)

2025-01-20 21:20 UTC, jimmykl commented
Can I request that if this feature is added it is easy to disable, either in UI settings or a config file? I wouldn't use this tool in my workflow and don't want it cluttering the UI. ✌️

2025-01-23 22:44 UTC, juli4nb4dillo commented
@jimmykl I tested displaying the SVG IO section only if a build-time var is on, I think I can make it with a runtime flag instead (which would be ideal), I'm figuring this out.

2025-03-05 00:29 UTC, juli4nb4dillo commented
Almost there, but for some reason it gets stuck on the final fetch.

2025-03-08 16:29 UTC, juli4nb4dillo commented
I tested this with my robot and works fine.
It's disabled by default, unless you run the server with the `--svgio-api-key` option.

2025-03-08 18:47 UTC, alexrudd2 commented
I think we're quite close to merging this now.

If I'm understanding correctly, the front-end needs to know whether or not SVG.io is enabled (i.e. whether there is an API key).  This is currently done by adding:
* `svgIoEnabled` added to the EBB `DeviceInfo`
* a `dev` websocket message between the Express server and the UI
* a `dev` method in `SaxiDriver` that sends the `dev` WS message.

This seems overly complicated to me.   
* Express knows the SVG.io info already since it's passed in `startServer`.  It doesn't need to be added EBB `DeviceInfo`.
* The websocket `dev` message should only happen once.
(1) Currently, Express adds a connection handler that will send the message, initiated by the server.
(2) It also adds parsing for a `dev` message from the client.
(3) Then React's `connect()` method on the same websocket calls `this.dev(); // request device info upon start` ?

I'll experiment a bit and see if the redundant messages can be removed.

Note: I assume it was intentional to not implement in `WebSerialDriver` since there are no command line arguments for that driver.

2025-03-10 04:13 UTC, alexrudd2 approved these changes
I think a CLI argument is a good solution for now (until/unless we develop a plugin system).

2025-03-10 04:14 UTC, merged